name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  full-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true
      - name: Build and install gem to systems gems
        run: bundle exec rake install
      - name: Run Linter
        run: bundle exec ci-helper RubocopLint
      - name: Check missed spec suffixes
        run: bundle exec ci-helper CheckSpecSuffixes --extra-paths spec/*.rb --ignored-paths spec/*_helper.rb
      - name: Run specs
        run: bundle exec ci-helper RunSpecs
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
  specs:
    runs-on: ubuntu-latest

    env:
      FULL_TEST_COVERAGE_CHECK: false

    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.2", "3.3", "3.4"]

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run specs
        run: bundle exec rspec
